name: Fetch Watching Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: ggfevans/trakt-json-bourne@79005a28f68a285f6a4295781138423402ec6623
        with:
          trakt_client_id: ${{ secrets.TRAKT_CLIENT_ID }}
          trakt_username: 'gvns'
          tmdb_api_key: ${{ secrets.TMDB_API_KEY }}

      - uses: ./.github/actions/commit-via-pr
        with:
          paths: src/data/watching.json
          commit-message: "chore: update watching data"
          branch-prefix: update-watching
          github-token: ${{ secrets.GH_PAT }}
